---
version: '3.8'
networks:
  vortex-dev:
services:
  db:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vortex
    volumes:
      - './postgres_db_data/data-plane:/var/lib/postgresql/data:z'
    command: postgres -c 'max_connections=1000'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - vortex-dev
  vortex-app-portal:
    image: cloudnexusopsdockerhub/vortex-app-portal:latest
    ports:
      - '3000:8080'
    environment:
      RUNTIME_API_BASE_URL: http://localhost:8000
    networks:
      - vortex-dev
  vortex-app-api:
    image: cloudnexusopsdockerhub/vortex-app-api:latest
    volumes:
      - >-
        ./app-api/application-default.yaml:/opt/app/config/application-default.yaml:ro
    ports:
      - '8000:8080'
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - vortex-dev
