export const ENV = {
  API_BASE_URL: process.env.API_BASE_URL,
  RESELLER_AUTH0_DOMAIN: process.env.AUTH0_DOMAIN,
  RESELLER_AUTH0_CLIENT_ID: process.env.AUTH0_CLIENT_ID,
  RESELLER_AUTH0_AUDIENCE: process.env.AUTH0_AUDIENCE,
  RESELLER_AUTH0_MGMT_ORG_ID: process.env.AUTH0_MGMT_ORG_ID,
  CUSTOMER_AUTH0_DOMAIN: process.env.CUSTOMER_AUTH0_DOMAIN,
  CUSTOMER_AUTH0_CLIENT_ID: process.env.CUSTOMER_AUTH0_CLIENT_ID,
  CUSTOMER_AUTH0_AUDIENCE: process.env.CUSTOMER_AUTH0_AUDIENCE,
  VORTEX_MODULES: process.env.VORTEX_MODULES,
  THEME_COLOR: process.env.THEME_COLOR,
  COMPANY_LOGO_URL: process.env.COMPANY_LOGO_URL,
  SPECIFICATIONS_LINK_URL: process.env.SPECIFICATIONS_LINK_URL,
  HELP_CENTER_URL: process.env.HELP_CENTER_URL,
  TERM_OF_USE_URL: process.env.TERM_OF_USE_URL,
  PRIVACY_STATEMENT_URL: process.env.PRIVACY_STATEMENT_URL,
  COOKIE_URL: process.env.COOKIE_URL,
  DOWNSTREAM_API_PREFIX: process.env.DOWNSTREAM_API_PREFIX,
  USING_MEF_STYLE: process.env.USING_MEF_STYLE,
  GET_DC_LIST_WITH_MEF: process.env.GET_DC_LIST_WITH_MEF,
  PRICING_PAYG_ENABLE: process.env.PRICING_PAYG_ENABLE,
  PRICING_PAYG_TOGGLE: process.env.PRICING_PAYG_TOGGLE,
  PRICING_PAYDOLLAR_URL: process.env.PRICING_PAYDOLLAR_URL,
  PRICING_PAYDOLLAR_PAYTYPE: process.env.PRICING_PAYDOLLAR_PAYTYPE,
  PRICING_PAYDOLLAR_MERCHANT_ID: process.env.PRICING_PAYDOLLAR_MERCHANT_ID,
  PRICING_PORT_INVOICE_PAYMENT: process.env.PRICING_PORT_INVOICE_PAYMENT,
  PRICING_CONNECTION_INVOICE_PAYMENT: process.env.PRICING_CONNECTION_INVOICE_PAYMENT,
  PRICING_CONNECTION_INVOICE_PAYMENT_CLOUD: process.env.PRICING_CONNECTION_INVOICE_PAYMENT_CLOUD,
  PRICING_CONNECTION_INVOICE_PAYMENT_TENCENT: process.env.PRICING_CONNECTION_INVOICE_PAYMENT_TENCENT,

}

export const CUSTOMER_AUTH0 = {
  domain: ENV.CUSTOMER_AUTH0_DOMAIN ?? '',
  clientId: ENV.CUSTOMER_AUTH0_CLIENT_ID ?? '',
  authorizationParams: {
    redirect_uri: window.location.origin,
    audience: ENV.CUSTOMER_AUTH0_AUDIENCE
  }
}

export const RESELLER_AUTH0 = {
  domain: ENV.RESELLER_AUTH0_DOMAIN ?? '',
  clientId: ENV.RESELLER_AUTH0_CLIENT_ID ?? '',
  authorizationParams: {
    redirect_uri: window.location.origin,
    audience: ENV.RESELLER_AUTH0_AUDIENCE
  }
}
