export const ENV = {
  API_BASE_URL: process.env.API_BASE_URL,
  RESELLER_AUTH0_DOMAIN: process.env.AUTH0_DOMAIN,
  RESELLER_AUTH0_CLIENT_ID: process.env.AUTH0_CLIENT_ID,
  RESELLER_AUTH0_AUDIENCE: process.env.AUTH0_AUDIENCE,
  RESELLER_AUTH0_MGMT_ORG_ID: process.env.AUTH0_MGMT_ORG_ID,
  CUSTOMER_AUTH0_DOMAIN: process.env.CUSTOMER_AUTH0_DOMAIN,
  CUSTOMER_AUTH0_CLIENT_ID: process.env.CUSTOMER_AUTH0_CLIENT_ID,
  CUSTOMER_AUTH0_AUDIENCE: process.env.CUSTOMER_AUTH0_AUDIENCE,
  VORTEX_MODULES: process.env.VORTEX_MODULES,
  THEME_COLOR: process.env.THEME_COLOR,
  COMPANY_LOGO_URL: process.env.COMPANY_LOGO_URL,
  SPECIFICATIONS_LINK_URL: process.env.SPECIFICATIONS_LINK_URL,
  HELP_CENTER_URL: process.env.HELP_CENTER_UR,
  TERM_OF_USE_URL: process.env.TERM_OF_USE_URL,
  PRIVACY_STATEMENT_URL: process.env.PRIVACY_STATEMENT_URL,
  COOKIE_URL: process.env.COOKIE_URL,
  DOWNSTREAM_API_PREFIX: process.env.DOWNSTREAM_API_PREFIX
}

export const CUSTOMER_AUTH0 = {
  domain: ENV.CUSTOMER_AUTH0_DOMAIN ?? '',
  clientId: ENV.CUSTOMER_AUTH0_CLIENT_ID ?? '',
  authorizationParams: {
    redirect_uri: window.location.origin,
    audience: ENV.CUSTOMER_AUTH0_AUDIENCE
  }
}

export const RESELLER_AUTH0 = {
  domain: ENV.RESELLER_AUTH0_DOMAIN ?? '',
  clientId: ENV.RESELLER_AUTH0_CLIENT_ID ?? '',
  authorizationParams: {
    redirect_uri: window.location.origin,
    audience: ENV.RESELLER_AUTH0_AUDIENCE
  }
}
