export const ENV = {
  API_BASE_URL: process.env.API_BASE_URL,
  AUTH0_DOMAIN: process.env.AUTH0_DOMAIN,
  AUTH0_CLIENT_ID: process.env.AUTH0_CLIENT_ID,
  AUTH0_AUDIENCE: process.env.AUTH0_AUDIENCE,
  AUTH0_MGMT_ORG_ID: process.env.AUTH0_MGMT_ORG_ID,
  VORTEX_MODULES: process.env.VORTEX_MODULES
}
