package com.consoleconnect.vortex.gateway.enums;

public enum TransformerIdentityEnum {
  DEFAULT_RESOURCE_CREATE,
  DEFAULT_RESOURCE_LIST,
  PORT_CONNECTION_LIST,
  PORT_ORDER_LIST,

  RESOURCE_CREATE,
  RESOURCES_LIST_AND_FILTER,
  RESOURCES_LIST_AND_MODIFY,
  RESOURCE_GET_AND_MODIFY,
  UNDEFINED;
}
