---
name: Create tag and release
on:
  workflow_dispatch:
    inputs:
      branch: 
        description: 'The branch checkout'
        required: false
        type: string
        default: 'main'

jobs:
  bump-version:
    name: Create release in ${{ inputs.branch }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Get the current version
        id: vars
        run: |
          git log -n 5
          CURRENT_VERSION=$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)
          echo $CURRENT_VERSION
          echo "current-version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: initialize git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Create git tag
        run: |
          git tag -a v${{ steps.vars.outputs.current-version }} -m v${{ steps.vars.outputs.current-version }}
          git push --tags

      - name: Create a PR for the new version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ steps.vars.outputs.current-version }} --generate-notes
