---
name: Dev release
on:
  workflow_dispatch:
    inputs:
      branch: 
        description: 'The branch checkout'
        required: false
        type: string
        default: 'main'
jobs:
  container_release:
    name: Build docker images and publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Get the current version
        id: vars
        run: |
          git log -n 5
          CURRENT_VERSION=$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)
          echo $CURRENT_VERSION
          echo "current-version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build vortex-app-api container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/app-api/Dockerfile
          push: true
          tags: "cloudnexusopsdockerhub/vortex-app-api:${{ steps.vars.outputs.current-version }}"

      - name: Build vortex-app-portal container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/app-portal/Dockerfile
          push: true
          tags: "cloudnexusopsdockerhub/vortex-app-portal:${{ steps.vars.outputs.current-version }}"
